"use client";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/YkxhHS1Nwal
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import ShinyButton from "../magicui/shiny-button";
import WordFadeIn from "../magicui/word-fade-in";
import { JSX, SVGProps } from "react";
import { ShinyComponent } from "./ShinyComponent";

export function CardIntroduction() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container px-4 md:px-6 flex flex-col items-center justify-center text-center space-y-6">
        <div className="space-y-4">
          <ShinyComponent />
          <h1
            className="sm:text-5xl md:text-6xl pointer-events-none z-10 h-full whitespace-pre-wrap bg-gradient-to-bl from-amber-400 via-[#012229] to-red-600 bg-clip-text text-transparent text-center text-6xl font-bold leading-none tracking-tighter  dark:drop-shadow-[0_5px_5px_rgba(0,0,0,0.8)] drop-shadow-[0_5px_5px_rgba(255,255,255)]   "
          >
            <WordFadeIn
              className="text-md "
              words="Capacitando um Futuro Sustentável"
            />
          </h1>
          <p className="font-bold max-w-[700] lg:max-w-[500px] text-[#000000] md:text-xl/relaxed lg:text-base/relaxed xl:text-2xl/relaxed">
            <WordFadeIn
              words="Junte-se a nós na nossa missão de combater as alterações climáticas e criar uma
            um mundo mais verde e mais resiliente para todos. Juntos, podemos fazer um
            impacto duradouro."
            />
          </p>
        </div>

        <ShinyButton text="Ingressar" />
      </div>
    </section>
  );
}

function CloudSunRainIcon(
  props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 2v2" />
      <path d="m4.93 4.93 1.41 1.41" />
      <path d="M20 12h2" />
      <path d="m19.07 4.93-1.41 1.41" />
      <path d="M15.947 12.65a4 4 0 0 0-5.925-4.128" />
      <path d="M3 20a5 5 0 1 1 8.9-4H13a3 3 0 0 1 2 5.24" />
      <path d="M11 20v2" />
      <path d="M7 19v2" />
    </svg>
  );
}
