/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/1GDksUcGor9
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Rubik } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { FilterIconProps } from "@/app/types";
import Link from "next/link";

export function FooterComponent() {
  return (
    <footer className="bg-gray-700 flex flex-col text-white py-12">
      <div className="flex justify-between px-8">
        <div className="flex flex-1 flex-col items-start gap-4">
          <Link href="#" className="flex items-center gap-2" prefetch={false}>
            <LeafIcon className="w-8 h-8 text-primary" />
            <span className="text-xl font-bold">Hackaton Climates</span>
          </Link>
          <p className="text-muted-foreground">
            Hackaton Climates é uma plataforma dedicada a abordar questões
            relacionadas ao clima por meio de esforços colaborativos e soluções
            inovadoras.
          </p>
          <div className="bg-background rounded-md p-4">
            <h4 className="text-lg font-semibold">Contribuidores do Projeto</h4>
            <div className="flex flex-col gap-2 mt-2">
              <Link
                href="https://www.instagram.com/bro.pereira"
                className="flex items-center gap-2"
                prefetch={false}
              >
                <UserIcon className="w-5 h-5 text-muted-foreground" />
                <span>Matheus Pereira - @bro.pereira</span>
              </Link>

              <Link
                href="https://www.instagram.com/_Luis.Silvah"
                className="flex items-center gap-2"
                prefetch={false}
              >
                <UserIcon className="w-5 h-5 text-muted-foreground" />
                <span>Luis Gustavo - @_luis.silvah</span>
              </Link>

              <Link
                href="https://www.instagram.com/brenowho"
                className="flex items-center gap-2"
                prefetch={false}
              >
                <UserIcon className="w-5 h-5 text-muted-foreground" />
                <span>Breno Pinho- @brenowho</span>
              </Link>

            </div>
          </div>
        </div>
        <div className="flex flex-1 justify-end gap-8">
          <div className="flex flex-col gap-2">
            <h4 className="text-lg font-semibold">Links Rápidos</h4>
            <Link
              href="#"
              className="text-muted-foreground hover:underline"
              prefetch={false}
            >
              Home
            </Link>
            <Link
              href="#"
              className="text-muted-foreground hover:underline"
              prefetch={false}
            >
              Eventos
            </Link>
          </div>
          <div className="flex flex-col gap-2">
            <h4 className="text-lg font-semibold">Siga-nos</h4>
            <div className="flex gap-4 items-start">
              <Link
                href="#"
                className=""
                prefetch={false}
              >
                <TwitterIcon className="w-6 h-6" />
              </Link>
              <Link
                href="#"
                className=""
                prefetch={false}
              >
                <InstagramIcon className="w-6 h-6" />
              </Link>
              <Link
                href="#"
                className=""
                prefetch={false}
              >
                <LinkedinIcon className="w-6 h-6" />
              </Link>
            </div>
          </div>
        </div>
      </div>
      <div className="container mx-auto mt-8 border-t pt-6 text-center text-muted-foreground">
        <p>&copy; 2024 Hackaton Climates. All rights reserved.</p>
      </div>
    </footer>
  );
}

function InstagramIcon(props: FilterIconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  );
}

function LeafIcon(props: FilterIconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M11 20A7 7 0 0 1 9.8 6.1C15.5 5 17 4.48 19 2c1 2 2 4.18 2 8 0 5.5-4.78 10-10 10Z" />
      <path d="M2 21c0-3 1.85-5.36 5.08-6C9.5 14.52 12 13 13 12" />
    </svg>
  );
}

function LinkedinIcon(props: FilterIconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  );
}

function TwitterIcon(props: FilterIconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  );
}

function UserIcon(props: FilterIconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  );
}
